version: '3'
services: 
  curso1:
    image: curso
    build: .
    command: node index.js
    ports:
      - "3000:3000"
    depends_on: 
      - "mongo"

  mongo: 
    image: "mongo"
    ports:
      - "27017:27017"
  